version: '3'
services:
  app:
    build: .
    volumes:
      - ./laravel-app:/var/www/html
    ports:
      - 8082:80
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
    networks:
      - mywebsite
    depends_on:
      - db    

  db:
    image: mysql:8.0
    container_name: mywebsitedb
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: mywebsitedb
      MYSQL_ROOT_PASSWORD: password
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - mywebsitedb:/var/lib/mysql
    ports:
      - 8083:3306
    networks:
      - mywebsite
          

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80
    networks:
      - mywebsite

  memcached:
    container_name: memcached
    image: memcached:latest
    ports:
        - 11211:11211
    networks:
      - mywebsite

networks:
    mywebsite:
        driver: bridge
volumes:
    mywebsitedb:
        driver: local
